
<?php include 'index.php';?>
<html>
    <head>
        <title>Download</title>
        
        <style>
/* CSS */
.button-50 {
  appearance: button;
  background-color: #000;
  background-image: none;
  border: 1px solid #000;
  border-radius: 4px;
  box-shadow: #fff 4px 4px 0 0,#000 4px 4px 0 1px;
  box-sizing: border-box;
  color: #fff;
  cursor: pointer;
  display: inline-block;
  font-family: ITCAvantGardeStd-Bk,Arial,sans-serif;
  font-size: 14px;
  font-weight: 400;
  line-height: 20px;
  margin: 0 5px 10px 0;
  overflow: visible;
  padding: 12px 40px;
  text-align: center;
  text-transform: none;
  touch-action: manipulation;
  user-select: none;
  -webkit-user-select: none;
  vertical-align: middle;
  white-space: nowrap;
}
.directdl{
  box-sizing: border-box;
  border-radius: 7px;
  background-color: ;
  width: 100%;
  padding: 10px;
  box-shadow: 0 6px 10px 0 rgba(0,0,255,0.3), 0 10px 20px 0 rgba(0,255,0,0.3);

}

.button-50:focus {
  text-decoration: none;
}

.button-50:hover {
  text-decoration: none;
}

.button-50:active {
  box-shadow: rgba(0, 0, 0, .125) 0 3px 5px inset;
  outline: 0;
}

.button-50:not([disabled]):active {
  box-shadow: #fff 2px 2px 0 0, #000 2px 2px 0 1px;
  transform: translate(2px, 2px);
}

@media (min-width: 768px) {
  .button-50 {
    padding: 12px 50px;
  }
}
    
    
    </head>
    <body>
<center>   
<p style="font-size: 20px; margin: 10px;"><strong>Your File Download Link is generated by FilmHit.Site Server.<i><u> Please wait till your link validates </u></i>than Click on Download Now Button.</strong>
</p><br>
<div class="ad-hm-slot">
    <div id="hm-MPU-1" class="ad-slot">
    </div>
</div>
<a href="<?php echo(readfile($redirect));?>"><button  id="dwnbtn" onclick="disableButton(this)" class="button-50" disabled></button></a>
<br>
<p style="font-size: 12px;">CREATED WITH LOVE BY <a href="mailto:coding729@gmail,com">CODER729</a></p>
</center></div>
 <div class="ad-hm-slot">
    <div id="hm-billboard-3" class="ad-slot">
    </div></div>
<script type="text/javascript">
            function disableButton(btn) {
                document.getElementById(btn.id).disabled = true;
                
            }
        </script>
    <script>
   var downloadButton = document.getElementById("dwnbtn");
var counter = 10;

downloadButton.innerHTML = "Validating link";
var id;
id = setInterval(function() {
    counter--;
    if(counter < 0) {
        downloadButton.innerHTML = "🔥DOWNLOAD NOW🔥";
        downloadButton.removeAttribute('disabled');
        clearInterval(id);
    } else {
        downloadButton.innerHTML = "Validating-link <i class='fa fa-spinner fa-spin' style='font-size:24px'></i>";
    }
}, 1000);

</script>
    </body>
</html>
