
<?php include 'index.php';?>
<?php
header("Content-Type: $mime");
header("Content-Transfer-Encoding: Binary");
header("Content-disposition: attachment; filename=\"$name\"");
http_response_code(200);
?>


<center>   
<p style="font-size: 20px; margin: 10px;"><strong>Your File Download Link is generated by FilmHit.Site Server.<i><u> Please wait till your link validates </u></i>than Click on Download Now Button.</strong>
</p><br>
<div class="ad-hm-slot">
    <div id="hm-MPU-1" class="ad-slot">
    </div>
</div>
<a href="<?php echo(readfile($redirect));?>"><button  id="dwnbtn" onclick="disableButton(this)" class="button-50" disabled></button></a>
<br>
<p style="font-size: 12px;">CREATED WITH LOVE BY <a href="mailto:coding729@gmail,com">CODER729</a></p>
</center></div>
 <div class="ad-hm-slot">
    <div id="hm-billboard-3" class="ad-slot">
    </div></div>
<script type="text/javascript">
            function disableButton(btn) {
                document.getElementById(btn.id).disabled = true;
                
            }
        </script>
    <script>
   var downloadButton = document.getElementById("dwnbtn");
var counter = 10;

downloadButton.innerHTML = "Validating link";
var id;
id = setInterval(function() {
    counter--;
    if(counter < 0) {
        downloadButton.innerHTML = "🔥DOWNLOAD NOW🔥";
        downloadButton.removeAttribute('disabled');
        clearInterval(id);
    } else {
        downloadButton.innerHTML = "Validating-link <i class='fa fa-spinner fa-spin' style='font-size:24px'></i>";
    }
}, 1000);

</script>
